---
abstract: 'ElasticSearch support for Data::SearchEngine'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-SearchEngine-ElasticSearch
requires:
  Clone: 0
  Data::SearchEngine::Paginator: 0
  Data::SearchEngine::Results: 0
  ElasticSearch: 0
  Moose: 0
  Try::Tiny: 0
resources:
  homepage: http://github.com/gphat/data-searchengine-elasticsearch
  repository: http://github.com/gphat/data-searchengine-elasticsearch
version: 0.03
